# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-19 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170411_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='fav_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='fav_count'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='trans_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='trans_count'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='viewed_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='viewed_count'),
        ),
    ]
