# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170920_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='source_name',
            field=models.TextField(blank=True, verbose_name='source_name'),
        ),
    ]
