# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170920_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Source'),
        ),
    ]
