# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170921_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title2'),
        ),
    ]
