# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogcategory_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='suggested_keywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='suggested_keywords'),
        ),
    ]
