# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170922_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-publish_date',), 'permissions': (('view_blogpost_list', 'Can view blogpost list'),), 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
    ]
