# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170926_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='review_status',
            field=models.IntegerField(choices=[(0, '\u672a\u5ba1\u6838'), (1, '\u5df2\u5ba1\u6838')], default=0, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
    ]
