# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-30 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogpost_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='fav_count',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='viewed_count',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='like_count'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='view_count'),
        ),
    ]
