# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 02:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_auto_20170930_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='review_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogpost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reviewed',
            field=models.DateTimeField(null=True, verbose_name='reviewed'),
        ),
    ]
