# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20171013_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='collect_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='collect_count'),
        ),
    ]
