# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_blogpost_sticky_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='like_count_v',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u865a\u62df\u70b9\u8d5e\u6570'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_count_v',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u865a\u62df\u9605\u8bfb\u6570'),
        ),
    ]
