# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('blog', '0020_auto_20171205_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': '\u5185\u5bb9\u7ba1\u7406\u5206\u7c7b',
                'verbose_name_plural': '\u5185\u5bb9\u7ba1\u7406\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='BlogFormCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': '\u5f62\u5f0f\u7ba1\u7406\u5206\u7c7b',
                'verbose_name_plural': '\u5f62\u5f0f\u7ba1\u7406\u5206\u7c7b',
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-publish_date',), 'permissions': (('view_blogpost_list', 'Can view blogpost list'), ('edit_operational_fields', 'can edit operational_fields')), 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='grade',
            field=models.IntegerField(choices=[(0, '\u666e\u901a'), (10, '\u826f\u597d'), (20, '\u9ad8\u8d28\u91cf')], default=0, verbose_name='\u6587\u7ae0\u8bc4\u7ea7'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_categories',
            field=models.ManyToManyField(blank=True, related_name='blogposts', to='blog.BlogContentCategory', verbose_name='\u5185\u5bb9\u7ba1\u7406\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='form_categories',
            field=models.ManyToManyField(blank=True, related_name='blogposts', to='blog.BlogFormCategory', verbose_name='\u5f62\u5f0f\u7ba1\u7406\u5206\u7c7b'),
        ),
    ]
