# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-19 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_auto_20170411_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedkeyword',
            name='weight',
            field=models.FloatField(blank=True, default=1, verbose_name='weight'),
        ),
    ]
